<?php

namespace TallSaas\View\Attributes;

trait StyleTrait
{
  public Style $style;

  public function style(
    Style\AlignContent $alignContent = null,
    Style\AlignItems $alignItems = null,
    Style\AlignSelf $alignSelf = null,
    Style\All $all = null,
    Style\Animation $animation = null,
    Style\AnimationDelay $animationDelay = null,
    Style\AnimationDirection $animationDirection = null,
    Style\AnimationDuration $animationDuration = null,
    Style\AnimationFillMode $animationFillMode = null,
    Style\AnimationIterationCount $animationIterationCount = null,
    Style\AnimationName $animationName = null,
    Style\AnimationPlayState $animationPlayState = null,
    Style\AnimationTimingFunction $animationTimingFunction = null,
    Style\BackfaceVisibility $backfaceVisibility = null,
    Style\Background $background = null,
    Style\BackgroundAttachment $backgroundAttachment = null,
    Style\BackgroundBlendMode $backgroundBlendMode = null,
    Style\BackgroundClip $backgroundClip = null,
    Style\BackgroundColor $backgroundColor = null,
    Style\BackgroundImage $backgroundImage = null,
    Style\BackgroundOrigin $backgroundOrigin = null,
    Style\BackgroundPosition $backgroundPosition = null,
    Style\BackgroundRepeat $backgroundRepeat = null,
    Style\BackgroundSize $backgroundSize = null,
    Style\Border $border = null,
    Style\BorderBottom $borderBottom = null,
    Style\BorderBottomColor $borderBottomColor = null,
    Style\BorderBottomLeftRadius $borderBottomLeftRadius = null,
    Style\BorderBottomRightRadius $borderBottomRightRadius = null,
    Style\BorderBottomStyle $borderBottomStyle = null,
    Style\BorderBottomWidth $borderBottomWidth = null,
    Style\BorderCollapse $borderCollapse = null,
    Style\BorderColor $borderColor = null,
    Style\BorderImage $borderImage = null,
    Style\BorderImageOutset $borderImageOutset = null,
    Style\BorderImageRepeat $borderImageRepeat = null,
    Style\BorderImageSlice $borderImageSlice = null,
    Style\BorderImageSource $borderImageSource = null,
    Style\BorderImageWidth $borderImageWidth = null,
    Style\BorderLeft $borderLeft = null,
    Style\BorderLeftColor $borderLeftColor = null,
    Style\BorderLeftStyle $borderLeftStyle = null,
    Style\BorderLeftWidth $borderLeftWidth = null,
    Style\BorderRadius $borderRadius = null,
    Style\BorderRight $borderRight = null,
    Style\BorderRightColor $borderRightColor = null,
    Style\BorderRightStyle $borderRightStyle = null,
    Style\BorderRightWidth $borderRightWidth = null,
    Style\BorderSpacing $borderSpacing = null,
    Style\BorderStyle $borderStyle = null,
    Style\BorderTop $borderTop = null,
    Style\BorderTopColor $borderTopColor = null,
    Style\BorderTopLeftRadius $borderTopLeftRadius = null,
    Style\BorderTopRightRadius $borderTopRightRadius = null,
    Style\BorderTopStyle $borderTopStyle = null,
    Style\BorderTopWidth $borderTopWidth = null,
    Style\BorderWidth $borderWidth = null,
    Style\Bottom $bottom = null,
    Style\BoxDecorationBreak $boxDecorationBreak = null,
    Style\BoxShadow $boxShadow = null,
    Style\BoxSizing $boxSizing = null,
    Style\BreakAfter $breakAfter = null,
    Style\BreakBefore $breakBefore = null,
    Style\BreakInside $breakInside = null,
    Style\CaptionSide $captionSide = null,
    Style\CaretColor $caretColor = null,
    Style\charset $charset = null,
    Style\Clear $clear = null,
    Style\Clip $clip = null,
    Style\ClipPath $clipPath = null,
    Style\Color $color = null,
    Style\ColumnCount $columnCount = null,
    Style\ColumnFill $columnFill = null,
    Style\ColumnGap $columnGap = null,
    Style\ColumnRule $columnRule = null,
    Style\ColumnRuleColor $columnRuleColor = null,
    Style\ColumnRuleStyle $columnRuleStyle = null,
    Style\ColumnRuleWidth $columnRuleWidth = null,
    Style\ColumnSpan $columnSpan = null,
    Style\ColumnWidth $columnWidth = null,
    Style\Columns $columns = null,
    Style\Content $content = null,
    Style\CounterIncrement $counterIncrement = null,
    Style\CounterReset $counterReset = null,
    Style\Cursor $cursor = null,
    Style\Direction $direction = null,
    Style\Display $display = null,
    Style\EmptyCells $emptyCells = null,
    Style\Filter $filter = null,
    Style\Flex $flex = null,
    Style\FlexBasis $flexBasis = null,
    Style\FlexDirection $flexDirection = null,
    Style\FlexFlow $flexFlow = null,
    Style\FlexGrow $flexGrow = null,
    Style\FlexShrink $flexShrink = null,
    Style\FlexWrap $flexWrap = null,
    Style\FloatDirection $float = null,
    Style\Font $font = null,
    Style\fontFace $fontFace = null,
    Style\FontFamily $fontFamily = null,
    Style\FontFeatureSettings $fontFeatureSettings = null,
    Style\FontKerning $fontKerning = null,
    Style\FontSize $fontSize = null,
    Style\FontSizeAdjust $fontSizeAdjust = null,
    Style\FontStretch $fontStretch = null,
    Style\FontStyle $fontStyle = null,
    Style\FontVariant $fontVariant = null,
    Style\FontVariantCaps $fontVariantCaps = null,
    Style\FontWeight $fontWeight = null,
    Style\Gap $gap = null,
    Style\Grid $grid = null,
    Style\GridArea $gridArea = null,
    Style\GridAutoColumns $gridAutoColumns = null,
    Style\GridAutoFlow $gridAutoFlow = null,
    Style\GridAutoRows $gridAutoRows = null,
    Style\GridColumn $gridColumn = null,
    Style\GridColumnEnd $gridColumnEnd = null,
    Style\GridColumnGap $gridColumnGap = null,
    Style\GridColumnStart $gridColumnStart = null,
    Style\GridGap $gridGap = null,
    Style\GridRow $gridRow = null,
    Style\GridRowEnd $gridRowEnd = null,
    Style\GridRowGap $gridRowGap = null,
    Style\GridRowStart $gridRowStart = null,
    Style\GridTemplate $gridTemplate = null,
    Style\GridTemplateAreas $gridTemplateAreas = null,
    Style\GridTemplateColumns $gridTemplateColumns = null,
    Style\GridTemplateRows $gridTemplateRows = null,
    Style\HangingPunctuation $hangingPunctuation = null,
    Style\Height $height = null,
    Style\Hyphens $hyphens = null,
    Style\ImageRendering $imageRendering = null,
    Style\import $import = null,
    Style\Isolation $isolation = null,
    Style\JustifyContent $justifyContent = null,
    Style\keyframes $keyframes = null,
    Style\Left $left = null,
    Style\LetterSpacing $letterSpacing = null,
    Style\LineHeight $lineHeight = null,
    Style\ListStyle $listStyle = null,
    Style\ListStyleImage $listStyleImage = null,
    Style\ListStylePosition $listStylePosition = null,
    Style\ListStyleType $listStyleType = null,
    Style\Margin $margin = null,
    Style\MarginBottom $marginBottom = null,
    Style\MarginLeft $marginLeft = null,
    Style\MarginRight $marginRight = null,
    Style\MarginTop $marginTop = null,
    Style\MaskImage $maskImage = null,
    Style\MaskMode $maskMode = null,
    Style\MaskOrigin $maskOrigin = null,
    Style\MaskPosition $maskPosition = null,
    Style\MaskRepeat $maskRepeat = null,
    Style\MaskSize $maskSize = null,
    Style\MaxHeight $maxHeight = null,
    Style\MaxWidth $maxWidth = null,
    Style\media $media = null,
    Style\MinHeight $minHeight = null,
    Style\MinWidth $minWidth = null,
    Style\MixBlendMode $mixBlendMode = null,
    Style\ObjectFit $objectFit = null,
    Style\ObjectPosition $objectPosition = null,
    Style\Opacity $opacity = null,
    Style\Order $order = null,
    Style\Orphans $orphans = null,
    Style\Outline $outline = null,
    Style\OutlineColor $outlineColor = null,
    Style\OutlineOffset $outlineOffset = null,
    Style\OutlineStyle $outlineStyle = null,
    Style\OutlineWidth $outlineWidth = null,
    Style\Overflow $overflow = null,
    Style\OverflowWrap $overflowWrap = null,
    Style\OverflowX $overflowX = null,
    Style\OverflowY $overflowY = null,
    Style\Padding $padding = null,
    Style\PaddingBottom $paddingBottom = null,
    Style\PaddingLeft $paddingLeft = null,
    Style\PaddingRight $paddingRight = null,
    Style\PaddingTop $paddingTop = null,
    Style\PageBreakAfter $pageBreakAfter = null,
    Style\PageBreakBefore $pageBreakBefore = null,
    Style\PageBreakInside $pageBreakInside = null,
    Style\Perspective $perspective = null,
    Style\PerspectiveOrigin $perspectiveOrigin = null,
    Style\PointerEvents $pointerEvents = null,
    Style\Position $position = null,
    Style\Quotes $quotes = null,
    Style\Resize $resize = null,
    Style\Right $right = null,
    Style\RowGap $rowGap = null,
    Style\ScrollBehavior $scrollBehavior = null,
    Style\TabSize $tabSize = null,
    Style\TableLayout $tableLayout = null,
    Style\TextAlign $textAlign = null,
    Style\TextAlignLast $textAlignLast = null,
    Style\TextDecoration $textDecoration = null,
    Style\TextDecorationColor $textDecorationColor = null,
    Style\TextDecorationLine $textDecorationLine = null,
    Style\TextDecorationStyle $textDecorationStyle = null,
    Style\TextDecorationThickness $textDecorationThickness = null,
    Style\TextIndent $textIndent = null,
    Style\TextJustify $textJustify = null,
    Style\TextOverflow $textOverflow = null,
    Style\TextShadow $textShadow = null,
    Style\TextTransform $textTransform = null,
    Style\Top $top = null,
    Style\Transform $transform = null,
    Style\TransformOrigin $transformOrigin = null,
    Style\TransformStyle $transformStyle = null,
    Style\Transition $transition = null,
    Style\TransitionDelay $transitionDelay = null,
    Style\TransitionDuration $transitionDuration = null,
    Style\TransitionProperty $transitionProperty = null,
    Style\TransitionTimingFunction $transitionTimingFunction = null,
    Style\UnicodeBidi $unicodeBidi = null,
    Style\UserSelect $userSelect = null,
    Style\VerticalAlign $verticalAlign = null,
    Style\Visibility $visibility = null,
    Style\WhiteSpace $whiteSpace = null,
    Style\Widows $widows = null,
    Style\Width $width = null,
    Style\WordBreak $wordBreak = null,
    Style\WordSpacing $wordSpacing = null,
    Style\WordWrap $wordWrap = null,
    Style\WritingMode $writingMode = null,
    Style\ZIndex $zIndex = null
  ): Style
  {
    if ($alignContent) $this->style->alignContent = $alignContent;
    if ($alignItems) $this->style->alignItems = $alignItems;
    if ($alignSelf) $this->style->alignSelf = $alignSelf;
    if ($all) $this->style->all = $all;
    if ($animation) $this->style->animation = $animation;
    if ($animationDelay) $this->style->animationDelay = $animationDelay;
    if ($animationDirection) $this->style->animationDirection = $animationDirection;
    if ($animationDuration) $this->style->animationDuration = $animationDuration;
    if ($animationFillMode) $this->style->animationFillMode = $animationFillMode;
    if ($animationIterationCount) $this->style->animationIterationCount = $animationIterationCount;
    if ($animationName) $this->style->animationName = $animationName;
    if ($animationPlayState) $this->style->animationPlayState = $animationPlayState;
    if ($animationTimingFunction) $this->style->animationTimingFunction = $animationTimingFunction;
    if ($backfaceVisibility) $this->style->backfaceVisibility = $backfaceVisibility;
    if ($background) $this->style->background = $background;
    if ($backgroundAttachment) $this->style->backgroundAttachment = $backgroundAttachment;
    if ($backgroundBlendMode) $this->style->backgroundBlendMode = $backgroundBlendMode;
    if ($backgroundClip) $this->style->backgroundClip = $backgroundClip;
    if ($backgroundColor) $this->style->backgroundColor = $backgroundColor;
    if ($backgroundImage) $this->style->backgroundImage = $backgroundImage;
    if ($backgroundOrigin) $this->style->backgroundOrigin = $backgroundOrigin;
    if ($backgroundPosition) $this->style->backgroundPosition = $backgroundPosition;
    if ($backgroundRepeat) $this->style->backgroundRepeat = $backgroundRepeat;
    if ($backgroundSize) $this->style->backgroundSize = $backgroundSize;
    if ($border) $this->style->border = $border;
    if ($borderBottom) $this->style->borderBottom = $borderBottom;
    if ($borderBottomColor) $this->style->borderBottomColor = $borderBottomColor;
    if ($borderBottomLeftRadius) $this->style->borderBottomLeftRadius = $borderBottomLeftRadius;
    if ($borderBottomRightRadius) $this->style->borderBottomRightRadius = $borderBottomRightRadius;
    if ($borderBottomStyle) $this->style->borderBottomStyle = $borderBottomStyle;
    if ($borderBottomWidth) $this->style->borderBottomWidth = $borderBottomWidth;
    if ($borderCollapse) $this->style->borderCollapse = $borderCollapse;
    if ($borderColor) $this->style->borderColor = $borderColor;
    if ($borderImage) $this->style->borderImage = $borderImage;
    if ($borderImageOutset) $this->style->borderImageOutset = $borderImageOutset;
    if ($borderImageRepeat) $this->style->borderImageRepeat = $borderImageRepeat;
    if ($borderImageSlice) $this->style->borderImageSlice = $borderImageSlice;
    if ($borderImageSource) $this->style->borderImageSource = $borderImageSource;
    if ($borderImageWidth) $this->style->borderImageWidth = $borderImageWidth;
    if ($borderLeft) $this->style->borderLeft = $borderLeft;
    if ($borderLeftColor) $this->style->borderLeftColor = $borderLeftColor;
    if ($borderLeftStyle) $this->style->borderLeftStyle = $borderLeftStyle;
    if ($borderLeftWidth) $this->style->borderLeftWidth = $borderLeftWidth;
    if ($borderRadius) $this->style->borderRadius = $borderRadius;
    if ($borderRight) $this->style->borderRight = $borderRight;
    if ($borderRightColor) $this->style->borderRightColor = $borderRightColor;
    if ($borderRightStyle) $this->style->borderRightStyle = $borderRightStyle;
    if ($borderRightWidth) $this->style->borderRightWidth = $borderRightWidth;
    if ($borderSpacing) $this->style->borderSpacing = $borderSpacing;
    if ($borderStyle) $this->style->borderStyle = $borderStyle;
    if ($borderTop) $this->style->borderTop = $borderTop;
    if ($borderTopColor) $this->style->borderTopColor = $borderTopColor;
    if ($borderTopLeftRadius) $this->style->borderTopLeftRadius = $borderTopLeftRadius;
    if ($borderTopRightRadius) $this->style->borderTopRightRadius = $borderTopRightRadius;
    if ($borderTopStyle) $this->style->borderTopStyle = $borderTopStyle;
    if ($borderTopWidth) $this->style->borderTopWidth = $borderTopWidth;
    if ($borderWidth) $this->style->borderWidth = $borderWidth;
    if ($bottom) $this->style->bottom = $bottom;
    if ($boxDecorationBreak) $this->style->boxDecorationBreak = $boxDecorationBreak;
    if ($boxShadow) $this->style->boxShadow = $boxShadow;
    if ($boxSizing) $this->style->boxSizing = $boxSizing;
    if ($breakAfter) $this->style->breakAfter = $breakAfter;
    if ($breakBefore) $this->style->breakBefore = $breakBefore;
    if ($breakInside) $this->style->breakInside = $breakInside;
    if ($captionSide) $this->style->captionSide = $captionSide;
    if ($caretColor) $this->style->caretColor = $caretColor;
    if ($charset) $this->style->charset = $charset;
    if ($clear) $this->style->clear = $clear;
    if ($clip) $this->style->clip = $clip;
    if ($clipPath) $this->style->clipPath = $clipPath;
    if ($color) $this->style->color = $color;
    if ($columnCount) $this->style->columnCount = $columnCount;
    if ($columnFill) $this->style->columnFill = $columnFill;
    if ($columnGap) $this->style->columnGap = $columnGap;
    if ($columnRule) $this->style->columnRule = $columnRule;
    if ($columnRuleColor) $this->style->columnRuleColor = $columnRuleColor;
    if ($columnRuleStyle) $this->style->columnRuleStyle = $columnRuleStyle;
    if ($columnRuleWidth) $this->style->columnRuleWidth = $columnRuleWidth;
    if ($columnSpan) $this->style->columnSpan = $columnSpan;
    if ($columnWidth) $this->style->columnWidth = $columnWidth;
    if ($columns) $this->style->columns = $columns;
    if ($content) $this->style->content = $content;
    if ($counterIncrement) $this->style->counterIncrement = $counterIncrement;
    if ($counterReset) $this->style->counterReset = $counterReset;
    if ($cursor) $this->style->cursor = $cursor;
    if ($direction) $this->style->direction = $direction;
    if ($display) $this->style->display = $display;
    if ($emptyCells) $this->style->emptyCells = $emptyCells;
    if ($filter) $this->style->filter = $filter;
    if ($flex) $this->style->flex = $flex;
    if ($flexBasis) $this->style->flexBasis = $flexBasis;
    if ($flexDirection) $this->style->flexDirection = $flexDirection;
    if ($flexFlow) $this->style->flexFlow = $flexFlow;
    if ($flexGrow) $this->style->flexGrow = $flexGrow;
    if ($flexShrink) $this->style->flexShrink = $flexShrink;
    if ($flexWrap) $this->style->flexWrap = $flexWrap;
    if ($float) $this->style->float = $float;
    if ($font) $this->style->font = $font;
    if ($fontFace) $this->style->fontFace = $fontFace;
    if ($fontFamily) $this->style->fontFamily = $fontFamily;
    if ($fontFeatureSettings) $this->style->fontFeatureSettings = $fontFeatureSettings;
    if ($fontKerning) $this->style->fontKerning = $fontKerning;
    if ($fontSize) $this->style->fontSize = $fontSize;
    if ($fontSizeAdjust) $this->style->fontSizeAdjust = $fontSizeAdjust;
    if ($fontStretch) $this->style->fontStretch = $fontStretch;
    if ($fontStyle) $this->style->fontStyle = $fontStyle;
    if ($fontVariant) $this->style->fontVariant = $fontVariant;
    if ($fontVariantCaps) $this->style->fontVariantCaps = $fontVariantCaps;
    if ($fontWeight) $this->style->fontWeight = $fontWeight;
    if ($gap) $this->style->gap = $gap;
    if ($grid) $this->style->grid = $grid;
    if ($gridArea) $this->style->gridArea = $gridArea;
    if ($gridAutoColumns) $this->style->gridAutoColumns = $gridAutoColumns;
    if ($gridAutoFlow) $this->style->gridAutoFlow = $gridAutoFlow;
    if ($gridAutoRows) $this->style->gridAutoRows = $gridAutoRows;
    if ($gridColumn) $this->style->gridColumn = $gridColumn;
    if ($gridColumnEnd) $this->style->gridColumnEnd = $gridColumnEnd;
    if ($gridColumnGap) $this->style->gridColumnGap = $gridColumnGap;
    if ($gridColumnStart) $this->style->gridColumnStart = $gridColumnStart;
    if ($gridGap) $this->style->gridGap = $gridGap;
    if ($gridRow) $this->style->gridRow = $gridRow;
    if ($gridRowEnd) $this->style->gridRowEnd = $gridRowEnd;
    if ($gridRowGap) $this->style->gridRowGap = $gridRowGap;
    if ($gridRowStart) $this->style->gridRowStart = $gridRowStart;
    if ($gridTemplate) $this->style->gridTemplate = $gridTemplate;
    if ($gridTemplateAreas) $this->style->gridTemplateAreas = $gridTemplateAreas;
    if ($gridTemplateColumns) $this->style->gridTemplateColumns = $gridTemplateColumns;
    if ($gridTemplateRows) $this->style->gridTemplateRows = $gridTemplateRows;
    if ($hangingPunctuation) $this->style->hangingPunctuation = $hangingPunctuation;
    if ($height) $this->style->height = $height;
    if ($hyphens) $this->style->hyphens = $hyphens;
    if ($imageRendering) $this->style->imageRendering = $imageRendering;
    if ($import) $this->style->import = $import;
    if ($isolation) $this->style->isolation = $isolation;
    if ($justifyContent) $this->style->justifyContent = $justifyContent;
    if ($keyframes) $this->style->keyframes = $keyframes;
    if ($left) $this->style->left = $left;
    if ($letterSpacing) $this->style->letterSpacing = $letterSpacing;
    if ($lineHeight) $this->style->lineHeight = $lineHeight;
    if ($listStyle) $this->style->listStyle = $listStyle;
    if ($listStyleImage) $this->style->listStyleImage = $listStyleImage;
    if ($listStylePosition) $this->style->listStylePosition = $listStylePosition;
    if ($listStyleType) $this->style->listStyleType = $listStyleType;
    if ($margin) $this->style->margin = $margin;
    if ($marginBottom) $this->style->marginBottom = $marginBottom;
    if ($marginLeft) $this->style->marginLeft = $marginLeft;
    if ($marginRight) $this->style->marginRight = $marginRight;
    if ($marginTop) $this->style->marginTop = $marginTop;
    if ($maskImage) $this->style->maskImage = $maskImage;
    if ($maskMode) $this->style->maskMode = $maskMode;
    if ($maskOrigin) $this->style->maskOrigin = $maskOrigin;
    if ($maskPosition) $this->style->maskPosition = $maskPosition;
    if ($maskRepeat) $this->style->maskRepeat = $maskRepeat;
    if ($maskSize) $this->style->maskSize = $maskSize;
    if ($maxHeight) $this->style->maxHeight = $maxHeight;
    if ($maxWidth) $this->style->maxWidth = $maxWidth;
    if ($media) $this->style->media = $media;
    if ($minHeight) $this->style->minHeight = $minHeight;
    if ($minWidth) $this->style->minWidth = $minWidth;
    if ($mixBlendMode) $this->style->mixBlendMode = $mixBlendMode;
    if ($objectFit) $this->style->objectFit = $objectFit;
    if ($objectPosition) $this->style->objectPosition = $objectPosition;
    if ($opacity) $this->style->opacity = $opacity;
    if ($order) $this->style->order = $order;
    if ($orphans) $this->style->orphans = $orphans;
    if ($outline) $this->style->outline = $outline;
    if ($outlineColor) $this->style->outlineColor = $outlineColor;
    if ($outlineOffset) $this->style->outlineOffset = $outlineOffset;
    if ($outlineStyle) $this->style->outlineStyle = $outlineStyle;
    if ($outlineWidth) $this->style->outlineWidth = $outlineWidth;
    if ($overflow) $this->style->overflow = $overflow;
    if ($overflowWrap) $this->style->overflowWrap = $overflowWrap;
    if ($overflowX) $this->style->overflowX = $overflowX;
    if ($overflowY) $this->style->overflowY = $overflowY;
    if ($padding) $this->style->padding = $padding;
    if ($paddingBottom) $this->style->paddingBottom = $paddingBottom;
    if ($paddingLeft) $this->style->paddingLeft = $paddingLeft;
    if ($paddingRight) $this->style->paddingRight = $paddingRight;
    if ($paddingTop) $this->style->paddingTop = $paddingTop;
    if ($pageBreakAfter) $this->style->pageBreakAfter = $pageBreakAfter;
    if ($pageBreakBefore) $this->style->pageBreakBefore = $pageBreakBefore;
    if ($pageBreakInside) $this->style->pageBreakInside = $pageBreakInside;
    if ($perspective) $this->style->perspective = $perspective;
    if ($perspectiveOrigin) $this->style->perspectiveOrigin = $perspectiveOrigin;
    if ($pointerEvents) $this->style->pointerEvents = $pointerEvents;
    if ($position) $this->style->position = $position;
    if ($quotes) $this->style->quotes = $quotes;
    if ($resize) $this->style->resize = $resize;
    if ($right) $this->style->right = $right;
    if ($rowGap) $this->style->rowGap = $rowGap;
    if ($scrollBehavior) $this->style->scrollBehavior = $scrollBehavior;
    if ($tabSize) $this->style->tabSize = $tabSize;
    if ($tableLayout) $this->style->tableLayout = $tableLayout;
    if ($textAlign) $this->style->textAlign = $textAlign;
    if ($textAlignLast) $this->style->textAlignLast = $textAlignLast;
    if ($textDecoration) $this->style->textDecoration = $textDecoration;
    if ($textDecorationColor) $this->style->textDecorationColor = $textDecorationColor;
    if ($textDecorationLine) $this->style->textDecorationLine = $textDecorationLine;
    if ($textDecorationStyle) $this->style->textDecorationStyle = $textDecorationStyle;
    if ($textDecorationThickness) $this->style->textDecorationThickness = $textDecorationThickness;
    if ($textIndent) $this->style->textIndent = $textIndent;
    if ($textJustify) $this->style->textJustify = $textJustify;
    if ($textOverflow) $this->style->textOverflow = $textOverflow;
    if ($textShadow) $this->style->textShadow = $textShadow;
    if ($textTransform) $this->style->textTransform = $textTransform;
    if ($top) $this->style->top = $top;
    if ($transform) $this->style->transform = $transform;
    if ($transformOrigin) $this->style->transformOrigin = $transformOrigin;
    if ($transformStyle) $this->style->transformStyle = $transformStyle;
    if ($transition) $this->style->transition = $transition;
    if ($transitionDelay) $this->style->transitionDelay = $transitionDelay;
    if ($transitionDuration) $this->style->transitionDuration = $transitionDuration;
    if ($transitionProperty) $this->style->transitionProperty = $transitionProperty;
    if ($transitionTimingFunction) $this->style->transitionTimingFunction = $transitionTimingFunction;
    if ($unicodeBidi) $this->style->unicodeBidi = $unicodeBidi;
    if ($userSelect) $this->style->userSelect = $userSelect;
    if ($verticalAlign) $this->style->verticalAlign = $verticalAlign;
    if ($visibility) $this->style->visibility = $visibility;
    if ($whiteSpace) $this->style->whiteSpace = $whiteSpace;
    if ($widows) $this->style->widows = $widows;
    if ($width) $this->style->width = $width;
    if ($wordBreak) $this->style->wordBreak = $wordBreak;
    if ($wordSpacing) $this->style->wordSpacing = $wordSpacing;
    if ($wordWrap) $this->style->wordWrap = $wordWrap;
    if ($writingMode) $this->style->writingMode = $writingMode;
    if ($zIndex) $this->style->zIndex = $zIndex;

    return $this->style;
  }
}