<?php

namespace TallSaas\View\Attributes;

trait StyleTrait
{
  public $style;

  public function style(
    Style\AlignContent|string $alignContent = null,
    Style\AlignItems|string $alignItems = null,
    Style\AlignSelf|string $alignSelf = null,
    Style\All|string $all = null,
    Style\Animation|string $animation = null,
    Style\AnimationDelay|string $animationDelay = null,
    Style\AnimationDirection|string $animationDirection = null,
    Style\AnimationDuration|string $animationDuration = null,
    Style\AnimationFillMode|string $animationFillMode = null,
    Style\AnimationIterationCount|string $animationIterationCount = null,
    Style\AnimationName|string $animationName = null,
    Style\AnimationPlayState|string $animationPlayState = null,
    Style\AnimationTimingFunction|string $animationTimingFunction = null,
    Style\BackfaceVisibility|string $backfaceVisibility = null,
    Style\Background|string $background = null,
    Style\BackgroundAttachment|string $backgroundAttachment = null,
    Style\BackgroundBlendMode|string $backgroundBlendMode = null,
    Style\BackgroundClip|string $backgroundClip = null,
    Style\BackgroundColor|string $backgroundColor = null,
    Style\BackgroundImage|string $backgroundImage = null,
    Style\BackgroundOrigin|string $backgroundOrigin = null,
    Style\BackgroundPosition|string $backgroundPosition = null,
    Style\BackgroundRepeat|string $backgroundRepeat = null,
    Style\BackgroundSize|string $backgroundSize = null,
    Style\Border|string $border = null,
    Style\BorderBottom|string $borderBottom = null,
    Style\BorderBottomColor|string $borderBottomColor = null,
    Style\BorderBottomLeftRadius|string $borderBottomLeftRadius = null,
    Style\BorderBottomRightRadius|string $borderBottomRightRadius = null,
    Style\BorderBottomStyle|string $borderBottomStyle = null,
    Style\BorderBottomWidth|string $borderBottomWidth = null,
    Style\BorderCollapse|string $borderCollapse = null,
    Style\BorderColor|string $borderColor = null,
    Style\BorderImage|string $borderImage = null,
    Style\BorderImageOutset|string $borderImageOutset = null,
    Style\BorderImageRepeat|string $borderImageRepeat = null,
    Style\BorderImageSlice|string $borderImageSlice = null,
    Style\BorderImageSource|string $borderImageSource = null,
    Style\BorderImageWidth|string $borderImageWidth = null,
    Style\BorderLeft|string $borderLeft = null,
    Style\BorderLeftColor|string $borderLeftColor = null,
    Style\BorderLeftStyle|string $borderLeftStyle = null,
    Style\BorderLeftWidth|string $borderLeftWidth = null,
    Style\BorderRadius|string $borderRadius = null,
    Style\BorderRight|string $borderRight = null,
    Style\BorderRightColor|string $borderRightColor = null,
    Style\BorderRightStyle|string $borderRightStyle = null,
    Style\BorderRightWidth|string $borderRightWidth = null,
    Style\BorderSpacing|string $borderSpacing = null,
    Style\BorderStyle|string $borderStyle = null,
    Style\BorderTop|string $borderTop = null,
    Style\BorderTopColor|string $borderTopColor = null,
    Style\BorderTopLeftRadius|string $borderTopLeftRadius = null,
    Style\BorderTopRightRadius|string $borderTopRightRadius = null,
    Style\BorderTopStyle|string $borderTopStyle = null,
    Style\BorderTopWidth|string $borderTopWidth = null,
    Style\BorderWidth|string $borderWidth = null,
    Style\Bottom|string $bottom = null,
    Style\BoxDecorationBreak|string $boxDecorationBreak = null,
    Style\BoxShadow|string $boxShadow = null,
    Style\BoxSizing|string $boxSizing = null,
    Style\BreakAfter|string $breakAfter = null,
    Style\BreakBefore|string $breakBefore = null,
    Style\BreakInside|string $breakInside = null,
    Style\CaptionSide|string $captionSide = null,
    Style\CaretColor|string $caretColor = null,
    Style\charset|string $charset = null,
    Style\Clear|string $clear = null,
    Style\Clip|string $clip = null,
    Style\ClipPath|string $clipPath = null,
    Style\Color|string $color = null,
    Style\ColumnCount|string $columnCount = null,
    Style\ColumnFill|string $columnFill = null,
    Style\ColumnGap|string $columnGap = null,
    Style\ColumnRule|string $columnRule = null,
    Style\ColumnRuleColor|string $columnRuleColor = null,
    Style\ColumnRuleStyle|string $columnRuleStyle = null,
    Style\ColumnRuleWidth|string $columnRuleWidth = null,
    Style\ColumnSpan|string $columnSpan = null,
    Style\ColumnWidth|string $columnWidth = null,
    Style\Columns|string $columns = null,
    Style\Content|string $content = null,
    Style\CounterIncrement|string $counterIncrement = null,
    Style\CounterReset|string $counterReset = null,
    Style\Cursor|string $cursor = null,
    Style\Direction|string $direction = null,
    Style\Display|string $display = null,
    Style\EmptyCells|string $emptyCells = null,
    Style\Filter|string $filter = null,
    Style\Flex|string $flex = null,
    Style\FlexBasis|string $flexBasis = null,
    Style\FlexDirection|string $flexDirection = null,
    Style\FlexFlow|string $flexFlow = null,
    Style\FlexGrow|string $flexGrow = null,
    Style\FlexShrink|string $flexShrink = null,
    Style\FlexWrap|string $flexWrap = null,
    Style\FloatDirection|string $float = null,
    Style\Font|string $font = null,
    Style\fontFace|string $fontFace = null,
    Style\FontFamily|string $fontFamily = null,
    Style\FontFeatureSettings|string $fontFeatureSettings = null,
    Style\FontKerning|string $fontKerning = null,
    Style\FontSize|string $fontSize = null,
    Style\FontSizeAdjust|string $fontSizeAdjust = null,
    Style\FontStretch|string $fontStretch = null,
    Style\FontStyle|string $fontStyle = null,
    Style\FontVariant|string $fontVariant = null,
    Style\FontVariantCaps|string $fontVariantCaps = null,
    Style\FontWeight|string $fontWeight = null,
    Style\Gap|string $gap = null,
    Style\Grid|string $grid = null,
    Style\GridArea|string $gridArea = null,
    Style\GridAutoColumns|string $gridAutoColumns = null,
    Style\GridAutoFlow|string $gridAutoFlow = null,
    Style\GridAutoRows|string $gridAutoRows = null,
    Style\GridColumn|string $gridColumn = null,
    Style\GridColumnEnd|string $gridColumnEnd = null,
    Style\GridColumnGap|string $gridColumnGap = null,
    Style\GridColumnStart|string $gridColumnStart = null,
    Style\GridGap|string $gridGap = null,
    Style\GridRow|string $gridRow = null,
    Style\GridRowEnd|string $gridRowEnd = null,
    Style\GridRowGap|string $gridRowGap = null,
    Style\GridRowStart|string $gridRowStart = null,
    Style\GridTemplate|string $gridTemplate = null,
    Style\GridTemplateAreas|string $gridTemplateAreas = null,
    Style\GridTemplateColumns|string $gridTemplateColumns = null,
    Style\GridTemplateRows|string $gridTemplateRows = null,
    Style\HangingPunctuation|string $hangingPunctuation = null,
    Style\Height|string $height = null,
    Style\Hyphens|string $hyphens = null,
    Style\ImageRendering|string $imageRendering = null,
    Style\import|string $import = null,
    Style\Isolation|string $isolation = null,
    Style\JustifyContent|string $justifyContent = null,
    Style\keyframes|string $keyframes = null,
    Style\Left|string $left = null,
    Style\LetterSpacing|string $letterSpacing = null,
    Style\LineHeight|string $lineHeight = null,
    Style\ListStyle|string $listStyle = null,
    Style\ListStyleImage|string $listStyleImage = null,
    Style\ListStylePosition|string $listStylePosition = null,
    Style\ListStyleType|string $listStyleType = null,
    Style\Margin|string $margin = null,
    Style\MarginBottom|string $marginBottom = null,
    Style\MarginLeft|string $marginLeft = null,
    Style\MarginRight|string $marginRight = null,
    Style\MarginTop|string $marginTop = null,
    Style\MaskImage|string $maskImage = null,
    Style\MaskMode|string $maskMode = null,
    Style\MaskOrigin|string $maskOrigin = null,
    Style\MaskPosition|string $maskPosition = null,
    Style\MaskRepeat|string $maskRepeat = null,
    Style\MaskSize|string $maskSize = null,
    Style\MaxHeight|string $maxHeight = null,
    Style\MaxWidth|string $maxWidth = null,
    Style\media|string $media = null,
    Style\MinHeight|string $minHeight = null,
    Style\MinWidth|string $minWidth = null,
    Style\MixBlendMode|string $mixBlendMode = null,
    Style\ObjectFit|string $objectFit = null,
    Style\ObjectPosition|string $objectPosition = null,
    Style\Opacity|string $opacity = null,
    Style\Order|string $order = null,
    Style\Orphans|string $orphans = null,
    Style\Outline|string $outline = null,
    Style\OutlineColor|string $outlineColor = null,
    Style\OutlineOffset|string $outlineOffset = null,
    Style\OutlineStyle|string $outlineStyle = null,
    Style\OutlineWidth|string $outlineWidth = null,
    Style\Overflow|string $overflow = null,
    Style\OverflowWrap|string $overflowWrap = null,
    Style\OverflowX|string $overflowX = null,
    Style\OverflowY|string $overflowY = null,
    Style\Padding|string $padding = null,
    Style\PaddingBottom|string $paddingBottom = null,
    Style\PaddingLeft|string $paddingLeft = null,
    Style\PaddingRight|string $paddingRight = null,
    Style\PaddingTop|string $paddingTop = null,
    Style\PageBreakAfter|string $pageBreakAfter = null,
    Style\PageBreakBefore|string $pageBreakBefore = null,
    Style\PageBreakInside|string $pageBreakInside = null,
    Style\Perspective|string $perspective = null,
    Style\PerspectiveOrigin|string $perspectiveOrigin = null,
    Style\PointerEvents|string $pointerEvents = null,
    Style\Position|string $position = null,
    Style\Quotes|string $quotes = null,
    Style\Resize|string $resize = null,
    Style\Right|string $right = null,
    Style\RowGap|string $rowGap = null,
    Style\ScrollBehavior|string $scrollBehavior = null,
    Style\TabSize|string $tabSize = null,
    Style\TableLayout|string $tableLayout = null,
    Style\TextAlign|string $textAlign = null,
    Style\TextAlignLast|string $textAlignLast = null,
    Style\TextDecoration|string $textDecoration = null,
    Style\TextDecorationColor|string $textDecorationColor = null,
    Style\TextDecorationLine|string $textDecorationLine = null,
    Style\TextDecorationStyle|string $textDecorationStyle = null,
    Style\TextDecorationThickness|string $textDecorationThickness = null,
    Style\TextIndent|string $textIndent = null,
    Style\TextJustify|string $textJustify = null,
    Style\TextOverflow|string $textOverflow = null,
    Style\TextShadow|string $textShadow = null,
    Style\TextTransform|string $textTransform = null,
    Style\Top|string $top = null,
    Style\Transform|string $transform = null,
    Style\TransformOrigin|string $transformOrigin = null,
    Style\TransformStyle|string $transformStyle = null,
    Style\Transition|string $transition = null,
    Style\TransitionDelay|string $transitionDelay = null,
    Style\TransitionDuration|string $transitionDuration = null,
    Style\TransitionProperty|string $transitionProperty = null,
    Style\TransitionTimingFunction|string $transitionTimingFunction = null,
    Style\UnicodeBidi|string $unicodeBidi = null,
    Style\UserSelect|string $userSelect = null,
    Style\VerticalAlign|string $verticalAlign = null,
    Style\Visibility|string $visibility = null,
    Style\WhiteSpace|string $whiteSpace = null,
    Style\Widows|string $widows = null,
    Style\Width|string $width = null,
    Style\WordBreak|string $wordBreak = null,
    Style\WordSpacing|string $wordSpacing = null,
    Style\WordWrap|string $wordWrap = null,
    Style\WritingMode|string $writingMode = null,
    Style\ZIndex|string $zIndex = null
  ): Style
  {
    if ($alignContent) $this->style->alignContent = $alignContent;
    if ($alignItems) $this->style->alignItems = $alignItems;
    if ($alignSelf) $this->style->alignSelf = $alignSelf;
    if ($all) $this->style->all = $all;
    if ($animation) $this->style->animation = $animation;
    if ($animationDelay) $this->style->animationDelay = $animationDelay;
    if ($animationDirection) $this->style->animationDirection = $animationDirection;
    if ($animationDuration) $this->style->animationDuration = $animationDuration;
    if ($animationFillMode) $this->style->animationFillMode = $animationFillMode;
    if ($animationIterationCount) $this->style->animationIterationCount = $animationIterationCount;
    if ($animationName) $this->style->animationName = $animationName;
    if ($animationPlayState) $this->style->animationPlayState = $animationPlayState;
    if ($animationTimingFunction) $this->style->animationTimingFunction = $animationTimingFunction;
    if ($backfaceVisibility) $this->style->backfaceVisibility = $backfaceVisibility;
    if ($background) $this->style->background = $background;
    if ($backgroundAttachment) $this->style->backgroundAttachment = $backgroundAttachment;
    if ($backgroundBlendMode) $this->style->backgroundBlendMode = $backgroundBlendMode;
    if ($backgroundClip) $this->style->backgroundClip = $backgroundClip;
    if ($backgroundColor) $this->style->backgroundColor = $backgroundColor;
    if ($backgroundImage) $this->style->backgroundImage = $backgroundImage;
    if ($backgroundOrigin) $this->style->backgroundOrigin = $backgroundOrigin;
    if ($backgroundPosition) $this->style->backgroundPosition = $backgroundPosition;
    if ($backgroundRepeat) $this->style->backgroundRepeat = $backgroundRepeat;
    if ($backgroundSize) $this->style->backgroundSize = $backgroundSize;
    if ($border) $this->style->border = $border;
    if ($borderBottom) $this->style->borderBottom = $borderBottom;
    if ($borderBottomColor) $this->style->borderBottomColor = $borderBottomColor;
    if ($borderBottomLeftRadius) $this->style->borderBottomLeftRadius = $borderBottomLeftRadius;
    if ($borderBottomRightRadius) $this->style->borderBottomRightRadius = $borderBottomRightRadius;
    if ($borderBottomStyle) $this->style->borderBottomStyle = $borderBottomStyle;
    if ($borderBottomWidth) $this->style->borderBottomWidth = $borderBottomWidth;
    if ($borderCollapse) $this->style->borderCollapse = $borderCollapse;
    if ($borderColor) $this->style->borderColor = $borderColor;
    if ($borderImage) $this->style->borderImage = $borderImage;
    if ($borderImageOutset) $this->style->borderImageOutset = $borderImageOutset;
    if ($borderImageRepeat) $this->style->borderImageRepeat = $borderImageRepeat;
    if ($borderImageSlice) $this->style->borderImageSlice = $borderImageSlice;
    if ($borderImageSource) $this->style->borderImageSource = $borderImageSource;
    if ($borderImageWidth) $this->style->borderImageWidth = $borderImageWidth;
    if ($borderLeft) $this->style->borderLeft = $borderLeft;
    if ($borderLeftColor) $this->style->borderLeftColor = $borderLeftColor;
    if ($borderLeftStyle) $this->style->borderLeftStyle = $borderLeftStyle;
    if ($borderLeftWidth) $this->style->borderLeftWidth = $borderLeftWidth;
    if ($borderRadius) $this->style->borderRadius = $borderRadius;
    if ($borderRight) $this->style->borderRight = $borderRight;
    if ($borderRightColor) $this->style->borderRightColor = $borderRightColor;
    if ($borderRightStyle) $this->style->borderRightStyle = $borderRightStyle;
    if ($borderRightWidth) $this->style->borderRightWidth = $borderRightWidth;
    if ($borderSpacing) $this->style->borderSpacing = $borderSpacing;
    if ($borderStyle) $this->style->borderStyle = $borderStyle;
    if ($borderTop) $this->style->borderTop = $borderTop;
    if ($borderTopColor) $this->style->borderTopColor = $borderTopColor;
    if ($borderTopLeftRadius) $this->style->borderTopLeftRadius = $borderTopLeftRadius;
    if ($borderTopRightRadius) $this->style->borderTopRightRadius = $borderTopRightRadius;
    if ($borderTopStyle) $this->style->borderTopStyle = $borderTopStyle;
    if ($borderTopWidth) $this->style->borderTopWidth = $borderTopWidth;
    if ($borderWidth) $this->style->borderWidth = $borderWidth;
    if ($bottom) $this->style->bottom = $bottom;
    if ($boxDecorationBreak) $this->style->boxDecorationBreak = $boxDecorationBreak;
    if ($boxShadow) $this->style->boxShadow = $boxShadow;
    if ($boxSizing) $this->style->boxSizing = $boxSizing;
    if ($breakAfter) $this->style->breakAfter = $breakAfter;
    if ($breakBefore) $this->style->breakBefore = $breakBefore;
    if ($breakInside) $this->style->breakInside = $breakInside;
    if ($captionSide) $this->style->captionSide = $captionSide;
    if ($caretColor) $this->style->caretColor = $caretColor;
    if ($charset) $this->style->charset = $charset;
    if ($clear) $this->style->clear = $clear;
    if ($clip) $this->style->clip = $clip;
    if ($clipPath) $this->style->clipPath = $clipPath;
    if ($color) $this->style->color = $color;
    if ($columnCount) $this->style->columnCount = $columnCount;
    if ($columnFill) $this->style->columnFill = $columnFill;
    if ($columnGap) $this->style->columnGap = $columnGap;
    if ($columnRule) $this->style->columnRule = $columnRule;
    if ($columnRuleColor) $this->style->columnRuleColor = $columnRuleColor;
    if ($columnRuleStyle) $this->style->columnRuleStyle = $columnRuleStyle;
    if ($columnRuleWidth) $this->style->columnRuleWidth = $columnRuleWidth;
    if ($columnSpan) $this->style->columnSpan = $columnSpan;
    if ($columnWidth) $this->style->columnWidth = $columnWidth;
    if ($columns) $this->style->columns = $columns;
    if ($content) $this->style->content = $content;
    if ($counterIncrement) $this->style->counterIncrement = $counterIncrement;
    if ($counterReset) $this->style->counterReset = $counterReset;
    if ($cursor) $this->style->cursor = $cursor;
    if ($direction) $this->style->direction = $direction;
    if ($display) $this->style->display = $display;
    if ($emptyCells) $this->style->emptyCells = $emptyCells;
    if ($filter) $this->style->filter = $filter;
    if ($flex) $this->style->flex = $flex;
    if ($flexBasis) $this->style->flexBasis = $flexBasis;
    if ($flexDirection) $this->style->flexDirection = $flexDirection;
    if ($flexFlow) $this->style->flexFlow = $flexFlow;
    if ($flexGrow) $this->style->flexGrow = $flexGrow;
    if ($flexShrink) $this->style->flexShrink = $flexShrink;
    if ($flexWrap) $this->style->flexWrap = $flexWrap;
    if ($float) $this->style->float = $float;
    if ($font) $this->style->font = $font;
    if ($fontFace) $this->style->fontFace = $fontFace;
    if ($fontFamily) $this->style->fontFamily = $fontFamily;
    if ($fontFeatureSettings) $this->style->fontFeatureSettings = $fontFeatureSettings;
    if ($fontKerning) $this->style->fontKerning = $fontKerning;
    if ($fontSize) $this->style->fontSize = $fontSize;
    if ($fontSizeAdjust) $this->style->fontSizeAdjust = $fontSizeAdjust;
    if ($fontStretch) $this->style->fontStretch = $fontStretch;
    if ($fontStyle) $this->style->fontStyle = $fontStyle;
    if ($fontVariant) $this->style->fontVariant = $fontVariant;
    if ($fontVariantCaps) $this->style->fontVariantCaps = $fontVariantCaps;
    if ($fontWeight) $this->style->fontWeight = $fontWeight;
    if ($gap) $this->style->gap = $gap;
    if ($grid) $this->style->grid = $grid;
    if ($gridArea) $this->style->gridArea = $gridArea;
    if ($gridAutoColumns) $this->style->gridAutoColumns = $gridAutoColumns;
    if ($gridAutoFlow) $this->style->gridAutoFlow = $gridAutoFlow;
    if ($gridAutoRows) $this->style->gridAutoRows = $gridAutoRows;
    if ($gridColumn) $this->style->gridColumn = $gridColumn;
    if ($gridColumnEnd) $this->style->gridColumnEnd = $gridColumnEnd;
    if ($gridColumnGap) $this->style->gridColumnGap = $gridColumnGap;
    if ($gridColumnStart) $this->style->gridColumnStart = $gridColumnStart;
    if ($gridGap) $this->style->gridGap = $gridGap;
    if ($gridRow) $this->style->gridRow = $gridRow;
    if ($gridRowEnd) $this->style->gridRowEnd = $gridRowEnd;
    if ($gridRowGap) $this->style->gridRowGap = $gridRowGap;
    if ($gridRowStart) $this->style->gridRowStart = $gridRowStart;
    if ($gridTemplate) $this->style->gridTemplate = $gridTemplate;
    if ($gridTemplateAreas) $this->style->gridTemplateAreas = $gridTemplateAreas;
    if ($gridTemplateColumns) $this->style->gridTemplateColumns = $gridTemplateColumns;
    if ($gridTemplateRows) $this->style->gridTemplateRows = $gridTemplateRows;
    if ($hangingPunctuation) $this->style->hangingPunctuation = $hangingPunctuation;
    if ($height) $this->style->height = $height;
    if ($hyphens) $this->style->hyphens = $hyphens;
    if ($imageRendering) $this->style->imageRendering = $imageRendering;
    if ($import) $this->style->import = $import;
    if ($isolation) $this->style->isolation = $isolation;
    if ($justifyContent) $this->style->justifyContent = $justifyContent;
    if ($keyframes) $this->style->keyframes = $keyframes;
    if ($left) $this->style->left = $left;
    if ($letterSpacing) $this->style->letterSpacing = $letterSpacing;
    if ($lineHeight) $this->style->lineHeight = $lineHeight;
    if ($listStyle) $this->style->listStyle = $listStyle;
    if ($listStyleImage) $this->style->listStyleImage = $listStyleImage;
    if ($listStylePosition) $this->style->listStylePosition = $listStylePosition;
    if ($listStyleType) $this->style->listStyleType = $listStyleType;
    if ($margin) $this->style->margin = $margin;
    if ($marginBottom) $this->style->marginBottom = $marginBottom;
    if ($marginLeft) $this->style->marginLeft = $marginLeft;
    if ($marginRight) $this->style->marginRight = $marginRight;
    if ($marginTop) $this->style->marginTop = $marginTop;
    if ($maskImage) $this->style->maskImage = $maskImage;
    if ($maskMode) $this->style->maskMode = $maskMode;
    if ($maskOrigin) $this->style->maskOrigin = $maskOrigin;
    if ($maskPosition) $this->style->maskPosition = $maskPosition;
    if ($maskRepeat) $this->style->maskRepeat = $maskRepeat;
    if ($maskSize) $this->style->maskSize = $maskSize;
    if ($maxHeight) $this->style->maxHeight = $maxHeight;
    if ($maxWidth) $this->style->maxWidth = $maxWidth;
    if ($media) $this->style->media = $media;
    if ($minHeight) $this->style->minHeight = $minHeight;
    if ($minWidth) $this->style->minWidth = $minWidth;
    if ($mixBlendMode) $this->style->mixBlendMode = $mixBlendMode;
    if ($objectFit) $this->style->objectFit = $objectFit;
    if ($objectPosition) $this->style->objectPosition = $objectPosition;
    if ($opacity) $this->style->opacity = $opacity;
    if ($order) $this->style->order = $order;
    if ($orphans) $this->style->orphans = $orphans;
    if ($outline) $this->style->outline = $outline;
    if ($outlineColor) $this->style->outlineColor = $outlineColor;
    if ($outlineOffset) $this->style->outlineOffset = $outlineOffset;
    if ($outlineStyle) $this->style->outlineStyle = $outlineStyle;
    if ($outlineWidth) $this->style->outlineWidth = $outlineWidth;
    if ($overflow) $this->style->overflow = $overflow;
    if ($overflowWrap) $this->style->overflowWrap = $overflowWrap;
    if ($overflowX) $this->style->overflowX = $overflowX;
    if ($overflowY) $this->style->overflowY = $overflowY;
    if ($padding) $this->style->padding = $padding;
    if ($paddingBottom) $this->style->paddingBottom = $paddingBottom;
    if ($paddingLeft) $this->style->paddingLeft = $paddingLeft;
    if ($paddingRight) $this->style->paddingRight = $paddingRight;
    if ($paddingTop) $this->style->paddingTop = $paddingTop;
    if ($pageBreakAfter) $this->style->pageBreakAfter = $pageBreakAfter;
    if ($pageBreakBefore) $this->style->pageBreakBefore = $pageBreakBefore;
    if ($pageBreakInside) $this->style->pageBreakInside = $pageBreakInside;
    if ($perspective) $this->style->perspective = $perspective;
    if ($perspectiveOrigin) $this->style->perspectiveOrigin = $perspectiveOrigin;
    if ($pointerEvents) $this->style->pointerEvents = $pointerEvents;
    if ($position) $this->style->position = $position;
    if ($quotes) $this->style->quotes = $quotes;
    if ($resize) $this->style->resize = $resize;
    if ($right) $this->style->right = $right;
    if ($rowGap) $this->style->rowGap = $rowGap;
    if ($scrollBehavior) $this->style->scrollBehavior = $scrollBehavior;
    if ($tabSize) $this->style->tabSize = $tabSize;
    if ($tableLayout) $this->style->tableLayout = $tableLayout;
    if ($textAlign) $this->style->textAlign = $textAlign;
    if ($textAlignLast) $this->style->textAlignLast = $textAlignLast;
    if ($textDecoration) $this->style->textDecoration = $textDecoration;
    if ($textDecorationColor) $this->style->textDecorationColor = $textDecorationColor;
    if ($textDecorationLine) $this->style->textDecorationLine = $textDecorationLine;
    if ($textDecorationStyle) $this->style->textDecorationStyle = $textDecorationStyle;
    if ($textDecorationThickness) $this->style->textDecorationThickness = $textDecorationThickness;
    if ($textIndent) $this->style->textIndent = $textIndent;
    if ($textJustify) $this->style->textJustify = $textJustify;
    if ($textOverflow) $this->style->textOverflow = $textOverflow;
    if ($textShadow) $this->style->textShadow = $textShadow;
    if ($textTransform) $this->style->textTransform = $textTransform;
    if ($top) $this->style->top = $top;
    if ($transform) $this->style->transform = $transform;
    if ($transformOrigin) $this->style->transformOrigin = $transformOrigin;
    if ($transformStyle) $this->style->transformStyle = $transformStyle;
    if ($transition) $this->style->transition = $transition;
    if ($transitionDelay) $this->style->transitionDelay = $transitionDelay;
    if ($transitionDuration) $this->style->transitionDuration = $transitionDuration;
    if ($transitionProperty) $this->style->transitionProperty = $transitionProperty;
    if ($transitionTimingFunction) $this->style->transitionTimingFunction = $transitionTimingFunction;
    if ($unicodeBidi) $this->style->unicodeBidi = $unicodeBidi;
    if ($userSelect) $this->style->userSelect = $userSelect;
    if ($verticalAlign) $this->style->verticalAlign = $verticalAlign;
    if ($visibility) $this->style->visibility = $visibility;
    if ($whiteSpace) $this->style->whiteSpace = $whiteSpace;
    if ($widows) $this->style->widows = $widows;
    if ($width) $this->style->width = $width;
    if ($wordBreak) $this->style->wordBreak = $wordBreak;
    if ($wordSpacing) $this->style->wordSpacing = $wordSpacing;
    if ($wordWrap) $this->style->wordWrap = $wordWrap;
    if ($writingMode) $this->style->writingMode = $writingMode;
    if ($zIndex) $this->style->zIndex = $zIndex;

    return $this->style;
  }
}